version: "3.8"

services:
  api:
    build: .
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]
    env_file:
      - .env
    volumes:
      - ./subscriptions.db:/app/subscriptions.db
    ports:
      - "8000:8000"
    restart: unless-stopped

  bot:
    build: .
    command: ["python", "bot.py"]
    env_file:
      - .env
    volumes:
      - ./subscriptions.db:/app/subscriptions.db
    restart: unless-stopped